---
- name: Make Datasaker Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: root
  with_items:
    - /etc/datasaker

- name: "Setting global-config"
  template:
    src: global-config.yml.j2
    dest: "/etc/datasaker/global-config.yml"